### ISSUE TITLE
Strikethrough component doesn't work.

### ISSUE THREAD

**Issue by stach** [evilstreak/markdown-js#302] opened 2018-01-06 08:12 UTC
```javascript
markdown.toHTML("Strikethrough uses two tildes. ~~Scratch this.~~")
"<p>Strikethrough uses two tildes. ~~Scratch this.~~</p>"
```

It does not work.

It should've returned this :
> Strikethrough uses two tildes. ~~Scratch this.~~

**Comment by ashb** [comment] 2018-01-06 15:39
Strikethrough is part of Github flavoured markdown, duplicate of #41

**Closed by ashb** 2018-01-06 15:39 UTC
