### ISSUE TITLE
``` to <pre><code>?

### ISSUE THREAD

**Issue by TIGERB** [evilstreak/markdown-js#287] opened 2017-02-12 13:09 UTC
For eample:

\```

\```
is interpreter to '\<p>\<code><\code><\p>' finnally 

but not the '\<pre>\<code><\code><\pre>';

why?

**Comment by ChrisZou** [comment] 2017-03-20 06:54
+1

**Comment by xiguaaxigua** [comment] 2017-03-25 17:06
+1

**Comment by nusje2000** [comment] 2017-03-30 13:29
+1

**Comment by SelinaYu** [comment] 2017-04-05 08:27
+1

**Comment by ashb** [comment] 2017-04-05 08:37
This is not "stock" markdown but part of Github Flavoured markdown, which no one has opened a pull request for yet.

Duplicate of #41.

**Closed by ashb** 2017-04-05 08:37 UTC
